const products = [
  {
    id: 1,
    name: 'guantes boxeo proyect',
    price: 18999,
    img: 'https://i.postimg.cc/Pq5728PJ/proyec-1.webp',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 2,
    name: 'guantes boxeo proyect',
    price: 18999,
    img: 'https://i.postimg.cc/K8QF5HPy/proyect-2.webp',
    stock: 22,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 3,
    name: 'guantes boxeo proyect',
    price: 18999,
    img: 'https://i.postimg.cc/vHW7xnpp/proyec-3.webp',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 4,
    name: 'guantes boxeo proyect',
    price: 18999,
    img: 'https://i.postimg.cc/2yrqbCVh/proyect4.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 5,
    name: 'Bucal',
    price: 3790,
    img: 'https://i.postimg.cc/0Q3WPHQT/bucal1.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 6,
    name: 'bucal',
    price: 1999,
    img: 'https://i.postimg.cc/P5xwQfKM/bucal10.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 7,
    name: 'bucal',
    price: 1999,
    img: 'https://i.postimg.cc/WbSZZqm3/bucal9.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 8,
    name: 'guantes adidas',
    price: 27999,
    img: 'https://i.postimg.cc/s2j0chqN/adidas1.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 9,
    name: 'vendas proyect',
    price: 5499,
    img: 'https://i.postimg.cc/pVFkKCyd/vendas1.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 10,
    name: 'vendas proyect',
    price: 5499,
    img: 'https://i.postimg.cc/DyQgMzrk/vendas2.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 11,
    name: 'bucal',
    price: 2999,
    img: 'https://i.postimg.cc/mkHdDN1t/bucal2.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 12,
    name: 'guantes de boxeo Adidas',
    price: 27999,
    img: 'https://i.postimg.cc/Y9ggLX8K/adidas2.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 13,
    name: 'guantes de boxeo Adidas',
    price: 27999,
    img: 'https://i.postimg.cc/15y64rq2/adidas3.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 14,
    name: 'vendas',
    price: 999,
    img: 'https://i.postimg.cc/brxQW62H/vendas12.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 15,
    name: 'vendas quuz',
    price: 3899,
    img: 'https://i.postimg.cc/RZVcpLCK/vendas13.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 16,
    name: 'kit inicial proyect',
    price: 28599,
    img: 'https://i.postimg.cc/0Q6nWdfc/pack-Proyect1.png',
    stock: 10,
    desc: 'descript',
    category: 'pack',
  },
  {
    id: 17,
    name: 'kit inicial proyect',
    price: 28599,
    img: 'https://i.postimg.cc/mD0w0zpR/pack-Proyect2.png',
    stock: 10,
    desc: 'descript',
    category: 'pack',
  },
  {
    id: 18,
    name: 'kit inicial Adidas',
    price: 34999,
    img: 'https://i.postimg.cc/xTLxV5SZ/pack-Adidas1.png',
    stock: 10,
    desc: 'descript',
    category: 'pack',
  },
  {
    id: 19,
    name: 'kit inicial Adidas',
    price: 34999,
    img: 'https://i.postimg.cc/dVvWsCsV/pack-Adidas2.png',
    stock: 10,
    desc: 'descript',
    category: 'pack',
  },
  {
    id: 20,
    name: 'bucal',
    price: 7899,
    img: 'https://i.postimg.cc/RCksY82f/bucal3.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 21,
    name: 'bucal',
    price: 1999,
    img: 'https://i.postimg.cc/XNR9xRXC/bucal4.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 22,
    name: 'guantes de boxeo drb',
    price: 23399,
    img: 'https://i.postimg.cc/L8Txns5B/drb1.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 23,
    name: 'guantes de boxeo proyect',
    price: 35999,
    img: 'https://i.postimg.cc/Wz8d0xkK/proyect01.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 24,
    name: 'guantes de boxeo proyect',
    price: 25999,
    img: 'https://i.postimg.cc/PqVKQFmC/proyect02.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 25,
    name: 'vendas venum',
    price: 8499,
    img: 'https://i.postimg.cc/t4SFKn7f/vendas10.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 26,
    name: 'guantes de boxeo venum',
    price: 45399,
    img: 'https://i.postimg.cc/VLFqFVwz/venum1.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 27,
    name: 'guantes de boxeo venum',
    price: 45399,
    img: 'https://i.postimg.cc/ZnSN8rD9/venum3.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 28,
    name: 'bucal profesional',
    price: 6999,
    img: 'https://i.postimg.cc/xjJptYpn/bucal5.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 29,
    name: 'guantes de boxeo venum',
    price: 69999,
    img: 'https://i.postimg.cc/050KgKBf/venum7.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 30,
    name: 'vendas proyect',
    price: 3899,
    img: 'https://i.postimg.cc/7LRM2Jk7/vendas4.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 31,
    name: 'venads proyect',
    price: 5999,
    img: 'https://i.postimg.cc/GmcQw1KB/vendas5.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 32,
    name: 'bucal profesional',
    price: 6999,
    img: 'https://i.postimg.cc/PxNVGktb/bucal6.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 33,
    name: 'bucal venum',
    price: 5999,
    img: 'https://i.postimg.cc/yxyZvkwL/bucal7.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 34,
    name: 'bucal profesional',
    price: 5999,
    img: 'https://i.postimg.cc/3wzmRMXF/bucal8.png',
    stock: 10,
    desc: 'descript',
    category: 'bucal',
  },
  {
    id: 35,
    name: 'vendas Venum',
    price: 8499,
    img: 'https://i.postimg.cc/CKnn9v3B/vendas11.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 36,
    name: 'vendas proyect',
    price: 5899,
    img: 'https://i.postimg.cc/ncf22mQG/vendas3.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 37,
    name: 'guantes de boxeo Venum',
    price: 87999,
    img: 'https://i.postimg.cc/zXdLvZ5H/venum6.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 38,
    name: 'vendas proyect',
    price: 4999,
    img: 'https://i.postimg.cc/SszL7QSP/vendas6.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 39,
    name: 'vendas Adidas',
    price: 7999,
    img: 'https://i.postimg.cc/bvr9rHKp/vendas8.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 40,
    name: 'vendas adidas',
    price: 7999,
    img: 'https://i.postimg.cc/FHDxhnCT/vendas7.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 40,
    name: 'guantes de boxeo Venum',
    price: 79999,
    img: 'https://i.postimg.cc/Nj5KrJfJ/venum5.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 41,
    name: 'vendas venum',
    price: 7999,
    img: 'https://i.postimg.cc/Fz5yPt1H/vendas9.png',
    stock: 10,
    desc: 'descript',
    category: 'vendas',
  },
  {
    id: 42,
    name: 'gauntes de boxeo venum',
    price: 97999,
    img: 'https://i.postimg.cc/FFy39B70/venum4.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 43,
    name: 'gauntes de boxeo Dragons',
    price: 37999,
    img: 'https://i.postimg.cc/tJHpk3K6/dragons1.png',
    stock: 10,
    desc: 'descript',
    category: 'guantes',
  },
  {
    id: 44,
    name: 'tibiales venum',
    price: 57999,
    img: 'https://i.postimg.cc/hjVqXJXt/tibiales7.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 45,
    name: 'kit muay thai Dragons',
    price: 59999,
    img: 'https://i.postimg.cc/mZQbDn9y/pack-Dragons1.png',
    stock: 10,
    desc: 'descript',
    category: 'pack',
  },
  {
    id: 46,
    name: 'kit muay thai Proyect',
    price: 44999,
    img: 'https://i.postimg.cc/fyjZr3sr/pack-Proyect3.png',
    stock: 10,
    desc: 'descript',
    category: 'pack',
  },
  {
    id: 47,
    name: 'tibiales dragons',
    price: 27399,
    img: 'https://i.postimg.cc/7YwqTNM8/tibiales1.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 48,
    name: 'tibiales proyect',
    price: 34499,
    img: 'https://i.postimg.cc/MK68Gpqz/tibiales10.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 49,
    name: 'tibiales sonnos',
    price: 15999,
    img: 'https://i.postimg.cc/Hs6181kX/tibiales11.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 50,
    name: 'tibiales proyect',
    price: 34499,
    img: 'https://i.postimg.cc/437GT2Zt/tibiales2.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 51,
    name: 'tibiales',
    price: 7999,
    img: 'https://i.postimg.cc/q7PTBcMF/tibiales3.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 52,
    name: 'tibiales dragons',
    price: 27399,
    img: 'https://i.postimg.cc/t4mbwG0p/tibiales4.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 53,
    name: 'tibiales trivo',
    price: 15399,
    img: 'https://i.postimg.cc/5Ngb5FnH/tibiales5.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 54,
    name: 'tibiales buddha',
    price: 29499,
    img: 'https://i.postimg.cc/htGg2P52/tibiales6.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 55,
    name: 'tibiales venum',
    price: 57399,
    img: 'https://i.postimg.cc/KjFhBZTr/tibiales8.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
  {
    id: 56,
    name: 'tibiales venum',
    price: 57399,
    img: 'https://i.postimg.cc/8kBSD68y/tibiales9.png',
    stock: 10,
    desc: 'descript',
    category: 'tibiales',
  },
]

export const getProducts = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(products)
    }, 800)
  })
}